apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-config
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
data:
  RABBITMQ_HOST: {{ include "ecommerce.rabbitmqHost" . }}
  {{- if .Values.mongodb.uri }}
  DB_URI: {{ .Values.mongodb.uri | quote }}
  {{- end }}
