apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce.fullname" . }}-mongodb
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.mongodb.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.mongodb.password | b64enc | quote }}
  DB_URL: {{ .Values.mongodb.url | b64enc | quote }}
